### PR TITLE
Default popup behavior functions

### PR DESCRIPTION
**Pull request by oschleic**
PRs relating to the v4 will be closed and locked.
* **Please check if the PR fulfills these requirements**
- [x] The PR is against the `development` branch
- [ ] Tests for the changes have been added (for bug fixes / features)
Not sure where to add tests
- [ ] Docs have been added / updated (for bug fixes / features)
Not sure where to add docs (plugins?)
- [x] Does NOT modify files under the "dist" folder.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...). If this is a fix, please tag a bug.

Default behavior for popups, allows for behavior to be overwritten with ```createPopup(element: HTMLElement, widget: HTMLElement, options: any): any``` and ```updatePopup(): void```

* **What is the current behavior?** (You can also link to an open issue here)

#2640

* **What is the new behavior (if this is a feature change)?**

Allows for custom popup behavior to be implemented in plugins.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No breaking change. 

* **Other information**:

Looking for some initial thoughts on this.

### CODE REVIEW

**Comment by oschleic** [comment]
@Eonasdan Curious on your thoughts here, don't want to go too far in the wrong direction

**Comment by oschleic** [comment]
Ah, no worries. There are no large drawbacks that I know of. It may be useful to throw an error if the import does not resolve, also need to change the type of the options parameter. Also should change the optional popper dependency to allow 2.X versions, or at least bump the version to latest.

If it works for you I'd be happy to fix this up and add documentation for it.

**Comment by Eonasdan** [comment]
That sounds good. If it needs to change later we can do that. Thanks again for this.

**Comment by oschleic** [comment]
Should be good to go now

**Comment by Eonasdan** [comment]
Thanks again for this

**Pull request merged**
