### PR TITLE
Reducing complexity of optionConverter

### PR DESCRIPTION
**Pull request by m-gallesio**
### Please check if the PR fulfills these requirements
- [X] The PR is against the `development` branch
- [X] Tests for the changes have been added (for bug fixes / features)
There is no test infrastructure ready, I ran some manual checks and they were successful.
- [ ] Docs have been added / updated (for bug fixes / features)
Not applicable, these are internal refactorings.
- [X] Does NOT modify files under the "dist" folder.

### What kind of change does this PR introduce?
This restructures the option validation code to reduce its complexity.
The single `switch` statement was split to separate properties of an object.
Some of its branches were almost identical; they have been unified by extracting their common behaviour in parametrized helpers.
A small bug was also fixed where 24 would be considered valid in `enabled/disabledHours` despite not doing anything.

### What is the current behavior?
See [this project item](https://github.com/Eonasdan/tempus-dominus/projects/3#card-65122166) which I mentioned [here](https://github.com/Eonasdan/tempus-dominus/discussions/2531).

### Does this PR introduce a breaking change?
As of now, it does not: since the methods I split off from optionConverter were public I kept them, redirecting to the split implementations.
I think this could be reconsidered, depending on how important they are to expose.
Due to these doubts, I have NOT updated the type definition files yet.

### Other information
See these blog posts for the file splitting procedure I used:
- https://devblogs.microsoft.com/oldnewthing/20190916-00/?p=102892
- https://devblogs.microsoft.com/oldnewthing/20190919-00/?p=102904

### CODE REVIEW

**Comment by Eonasdan** [comment]
Wow. Thanks for this. 

As far as tests go, no. It's been on my todo list as well. I wanted to reach 6.0 release before bothering with that. The one "test" is just to make sure I don't break the TS imports lol.

**Comment by m-gallesio** [comment]
We all know testing is not easy.
I will work on finalizing this, then.

**Comment by m-gallesio** [comment]
I ran some option checks and it seems to work. @Eonasdan This should be ready.

**Comment by Eonasdan** [comment]
Thanks again.

Do you have a good TS testing framework?

**Comment by m-gallesio** [comment]
Unfortunately no and I acknowledge this is a problem. I would rather have someone more knowledgeable chime in.

**Comment by Eonasdan** [comment]
@m-gallesio I added vitest and built tests around the DateTime object! It's pretty easy to use. I'm hoping to start building tests around the rest as I can

**Pull request merged**
